DROP TABLE CONTIENT;

DROP TABLE AFFECTATIONMATERIEL;

DROP TABLE TACHE;

DROP TABLE AFFECTATIONPERSONNEL;

DROP TABLE PROJET;

DROP TABLE PERSONNE;

DROP TABLE MATERIEL;

DROP TABLE DEPARTEMENT;

DROP SEQUENCE SEQ_DEPARTEMENT;

DROP SEQUENCE SEQ_MATERIEL;

DROP SEQUENCE SEQ_PERSONNE;

DROP SEQUENCE SEQ_PROJET;

DROP SEQUENCE SEQ_TACHE;

-- DELETE DONNER FROM TABLES

DELETE FROM CONTIENT;
DELETE FROM AFFECTATIONMATERIEL;
DELETE FROM AFFECTATIONPERSONNEL;
DELETE FROM TACHE;
DELETE FROM PROJET;
DELETE FROM PERSONNE;
DELETE FROM MATERIEL;
DELETE FROM DEPARTEMENT;

